/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsRagRouteImport } from './routes/apps/rag'
import { Route as AppsPapieRouteImport } from './routes/apps/papie'
import { Route as AppsHotnews4uRouteImport } from './routes/apps/hotnews4u'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRagRoute = AppsRagRouteImport.update({
  id: '/apps/rag',
  path: '/apps/rag',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsPapieRoute = AppsPapieRouteImport.update({
  id: '/apps/papie',
  path: '/apps/papie',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsHotnews4uRoute = AppsHotnews4uRouteImport.update({
  id: '/apps/hotnews4u',
  path: '/apps/hotnews4u',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps/hotnews4u': typeof AppsHotnews4uRoute
  '/apps/papie': typeof AppsPapieRoute
  '/apps/rag': typeof AppsRagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps/hotnews4u': typeof AppsHotnews4uRoute
  '/apps/papie': typeof AppsPapieRoute
  '/apps/rag': typeof AppsRagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps/hotnews4u': typeof AppsHotnews4uRoute
  '/apps/papie': typeof AppsPapieRoute
  '/apps/rag': typeof AppsRagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apps/hotnews4u' | '/apps/papie' | '/apps/rag'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apps/hotnews4u' | '/apps/papie' | '/apps/rag'
  id: '__root__' | '/' | '/apps/hotnews4u' | '/apps/papie' | '/apps/rag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsHotnews4uRoute: typeof AppsHotnews4uRoute
  AppsPapieRoute: typeof AppsPapieRoute
  AppsRagRoute: typeof AppsRagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/rag': {
      id: '/apps/rag'
      path: '/apps/rag'
      fullPath: '/apps/rag'
      preLoaderRoute: typeof AppsRagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/papie': {
      id: '/apps/papie'
      path: '/apps/papie'
      fullPath: '/apps/papie'
      preLoaderRoute: typeof AppsPapieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/hotnews4u': {
      id: '/apps/hotnews4u'
      path: '/apps/hotnews4u'
      fullPath: '/apps/hotnews4u'
      preLoaderRoute: typeof AppsHotnews4uRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsHotnews4uRoute: AppsHotnews4uRoute,
  AppsPapieRoute: AppsPapieRoute,
  AppsRagRoute: AppsRagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
